//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------
package Analisis;

/**
 * CUP generated class containing symbol constants.
 */
public class TablaSimbolos {
    /* terminals */

    public static final int tcontenido = 17;
    public static final int icontenido = 14;
    public static final int fdirectorio = 5;
    public static final int iestructura = 2;
    public static final int tdirectorio = 16;
    public static final int idirectorio = 4;
    public static final int terrorlex = 19;
    public static final int fnombre = 9;
    public static final int festructura = 3;
    public static final int EOF = 0;
    public static final int fcarpeta = 7;
    public static final int icarpeta = 6;
    public static final int error = 1;
    public static final int tnumero = 18;
    public static final int idocumento = 10;
    public static final int inombre = 8;
    public static final int fformato = 13;
    public static final int iformato = 12;
    public static final int talfanumerico = 20;
    public static final int fcontenido = 15;
    public static final int fdocumento = 11;
    public static final String[] terminalNames = new String[]{
        "EOF",
        "error",
        "iestructura",
        "festructura",
        "idirectorio",
        "fdirectorio",
        "icarpeta",
        "fcarpeta",
        "inombre",
        "fnombre",
        "idocumento",
        "fdocumento",
        "iformato",
        "fformato",
        "icontenido",
        "fcontenido",
        "tdirectorio",
        "tcontenido",
        "tnumero",
        "terrorlex",
        "talfanumerico"
    };
}
